version: "3.2"
services:
  nginx:
    image: nginx:alpine
    container_name: loteria-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - loteria
  db:
    image: postgres
    container_name: loteria-db-postgresql
    restart: unless-stopped
    env_file:
      - ./env/loteria.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: loteria
      POSTGRES_USER: homestad
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - loteria

  app:
    build:
      args:
        user: userloteria
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    image: loteria
    container_name: loteria-app-laravel
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www
    networks:
      - loteria

networks:
  loteria:
    driver: bridge
